image:
  repository: k8scc01covidacr.azurecr.io/hive-metastore
  tag: 767768aa5243cd22054badc7115a5abb764f07ba
  pullPolicy: IfNotPresent

postgresql:
  auth:
    username: ${ENV:HIVE-POSTGRES-USERNAME}
    password: ${ENV:HIVE-POSTGRES-PASSWORD}

replicas: 1
resources: {}
conf:
  hiveSite:
    hive_metastore_uris: thrift://hive-metastore:9083
    hive.metastore.warehouse.dir: /user/hive/warehouse

env:
  - name: HIVE-POSTGRES-USERNAME
    valueFrom:
      secretKeyRef: 
        name: hive-postgres-credentials 
        key: HIVE_PSQL_USERNAME

  - name: HIVE-POSTGRES-PASSWORD
    valueFrom:
      secretKeyRef: 
        name: hive-postgres-credentials 
        key: HIVE_PSQL_PASSWORD